Updates

diff --git a/run_onchange_020_install_oh_my_zsh.sh.tmpl b/run_onchange_020_install_oh_my_zsh.sh.tmpl
--- a/run_onchange_020_install_oh_my_zsh.sh.tmpl
+++ b/run_onchange_020_install_oh_my_zsh.sh.tmpl
@@ -14,6 +14,17 @@ fi
 
 log_info "Installing oh-my-zsh..."
 
+if ! has_program zsh; then
+	log_info "Missing zsh, installing..."
+	if os_is_darwin; then
+		brew install zsh
+	fi
+	if os_is_archlinux; then
+		sudo pacman -Sy --noconfirm zsh
+	fi
+fi
+
 export KEEP_ZSHRC=yes
 export OVERWRITE_CONFIRMATION=no
+
 sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
